#!/usr/bin/env node
/**
 * fetch-gauges.mjs — bake each declared USGS gauge's NAME and POSITION, once.
 *
 * WHY THIS EXISTS. The app has always known its gauges by number. The name a
 * reader would actually type — Freeport, Rio Vista, Verona — and the point on
 * the map only ever arrived with a LIVE reading, because both come down inside
 * the instantaneous-values payload the app fetches for the water level.
 *
 * That was fine while the only question was "what is the river doing". It is
 * not fine now that the reader can SEARCH. A search index built from live
 * payloads finds Freeport on a good connection and finds nothing on a bank with
 * no bars, or on a first run, or for a river whose panel has not been opened
 * this session — which is every condition this app is built for. Search that
 * works only when the network does is worse than no search: it teaches the
 * reader the place is not in here.
 *
 * So the names and positions ship with the build. They are still USGS's, still
 * fetched from USGS, never transcribed — the same rule as the tide stations,
 * and only the moment changes. The live payload still wins when it arrives.
 *
 *   node tools/fetch-gauges.mjs            write public/gauge-sites.js
 *   node tools/fetch-gauges.mjs --check    verify the committed file
 *
 * `--check` does NOT re-fetch, for the reason fetch-stations.mjs gives: it runs
 * in CI and on machines with no route to USGS, and a check that needs a third
 * party to be up goes red for reasons that are nobody's fault. It verifies the
 * file is present, parses, carries its provenance, and covers every gauge the
 * app declares.
 *
 * THERE IS NO SCHEDULE, deliberately, and that is the difference from the tide
 * stations. A gauge does not move, so a monthly re-fetch would rewrite the same
 * numbers with a new timestamp forever. What DOES change is the set the app
 * declares — and the day somebody adds one, `--check` goes red naming it, which
 * is the moment a re-bake is worth anything.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { spawnSync } from 'node:child_process';

/* Node's own fetch ignores HTTPS_PROXY unless NODE_USE_ENV_PROXY is set, and it
   reads it at STARTUP. Without it this prints "USGS answered 403" — the proxy's
   allowlist reply wearing USGS's name. (Hub LESSONS §173.) */
if (!process.argv.includes('--check') && !process.env.NODE_USE_ENV_PROXY &&
    (process.env.HTTPS_PROXY || process.env.https_proxy)) {
  const r = spawnSync(process.execPath, [import.meta.filename, ...process.argv.slice(2)],
    { stdio: 'inherit', env: { ...process.env, NODE_USE_ENV_PROXY: '1' } });
  process.exit(r.status === null ? 1 : r.status);
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'public', 'index.html');
const OUT = join(ROOT, 'public', 'gauge-sites.js');
const CHECK = process.argv.includes('--check');

/* The ids the app declares, read out of the app rather than restated here — the
   same reason fetch-stations reads its URL out of the app. A second list is a
   second thing to keep true, and it would go stale silently. */
function declaredIds(src) {
  const ids = [...src.matchAll(/\{\s*id:'(\d{8,16})'\s*,\s*status:PROV\./g)].map((m) => m[1]);
  if (!ids.length) throw new Error('no declared gauges in public/index.html — the shape changed');
  return [...new Set(ids)];
}

const src = readFileSync(SRC, 'utf8');
const want = declaredIds(src);

if (CHECK) {
  let file;
  try { file = readFileSync(OUT, 'utf8'); }
  catch { fail('public/gauge-sites.js is missing — run node tools/fetch-gauges.mjs'); }
  if (!/GENERATED by tools\/fetch-gauges\.mjs/.test(file)) fail('public/gauge-sites.js has lost its generated header');
  const scope = {};
  try { new Function('g', file + '\ng.META = GAUGE_SITES_META; g.SITES = GAUGE_SITES;')(scope); }
  catch (e) { fail('public/gauge-sites.js does not parse: ' + e.message); }
  if (!scope.META || !scope.META.fetchedAt || !scope.META.source)
    fail('public/gauge-sites.js has lost its provenance (fetchedAt / source)');
  const missing = want.filter((id) => !scope.SITES[id]);
  if (missing.length)
    fail(`${missing.length} declared gauge(s) are not baked: ${missing.join(', ')}\n` +
         '  run node tools/fetch-gauges.mjs');
  const bad = Object.entries(scope.SITES).filter(([, s]) =>
    !s.name || !Number.isFinite(s.lat) || !Number.isFinite(s.lon));
  if (bad.length) fail(`${bad.length} baked gauge(s) have no name or no position: ${bad.map(([i]) => i).join(', ')}`);
  console.log(`gauge sites: ${Object.keys(scope.SITES).length} baked, all ${want.length} declared gauge(s) covered, fetched ${scope.META.fetchedAt}`);
  process.exit(0);
}

function fail(msg) { console.error('FAIL  ' + msg); process.exit(1); }

const SITE = 'https://waterservices.usgs.gov/nwis/site/';
const url = SITE + '?format=rdb&sites=' + want.join(',');
console.log(`asking USGS for ${want.length} site record(s)`);
const res = await fetch(url, { headers: { accept: 'text/plain' } });
if (!res.ok) fail(`USGS answered ${res.status} for the site service`);
const text = await res.text();

/* RDB: comment lines, then a header row, then a widths row, then the data. */
const lines = text.split('\n').filter((l) => l && !l.startsWith('#'));
const head = lines.shift().split('\t');
lines.shift();
const col = (n) => { const i = head.indexOf(n); if (i < 0) fail(`USGS's answer has no ${n} column`); return i; };
const cNo = col('site_no'), cNm = col('station_nm'), cLat = col('dec_lat_va'), cLon = col('dec_long_va');

const sites = {};
for (const line of lines) {
  const f = line.split('\t');
  const id = (f[cNo] || '').trim();
  const lat = Number(f[cLat]), lon = Number(f[cLon]);
  if (!id || !Number.isFinite(lat) || !Number.isFinite(lon)) continue;
  sites[id] = { name: (f[cNm] || '').trim(), lat, lon };
}

/* A missing site is a FAILURE, not a smaller file. The app declares this gauge;
   if USGS will not say where it is, that is worth stopping for rather than
   quietly shipping a search that cannot find it. */
const missing = want.filter((id) => !sites[id]);
if (missing.length) fail(`USGS returned no position for: ${missing.join(', ')}`);

const esc = (v) => String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const body = want.map((id) =>
  `  '${esc(id)}': {name:'${esc(sites[id].name)}',lat:${sites[id].lat},lon:${sites[id].lon}}`).join(',\n');

writeFileSync(OUT, `/* GENERATED by tools/fetch-gauges.mjs — do not edit.
 *
 * USGS's own name and position for every gauge this app declares, fetched once
 * and shipped, so the reader can SEARCH for Freeport before any reading has
 * arrived — on a first run, offline, or on a river whose panel is still shut.
 *
 * These are USGS's numbers. Nothing here was typed by hand. A live reading
 * still carries its own name and position and still wins when it arrives. */
var GAUGE_SITES_META = {
  fetchedAt: '${new Date().toISOString()}',
  source: '${SITE}'
};
var GAUGE_SITES = {
${body}
};
`);
console.log(`wrote public/gauge-sites.js — ${want.length} gauge(s)`);
